#!/bin/sh -x
g++ $@ -Wall /mnt/e/Dropbox/My_Stuff/Minesweeper/Simple_CPP/simplecpp/lib/libsprite.a -I/mnt/e/Dropbox/My_Stuff/Minesweeper/Simple_CPP/simplecpp/include -I/usr/include/X11 -L/usr/X11R6/lib -lX11 -std=c++11
